POST localhost:3000/filter
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "topic": "test",
  "q": "sicp2"
}

###

GET localhost:3000/filter
Accept: application/json
Cache-Control: no-cache

###


GET localhost:3000/filter?id=2
Accept: application/json
Cache-Control: no-cache

######


DELETE localhost:3000/filter
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "id": 1
}



###